version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    container_name: go_app
    depends_on:
      - mongodb
    volumes:
      - ./backups:/app/backups
    entrypoint: ["sleep", "infinity"]
